jobs:
  build:
    name: Pull and Push to Aliyun
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      run: |
          echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login ${{ secrets.ALIYUN_REGISTRY }} -u ${{ secrets.ALIYUN_REGISTRY_USER }} --password-stdin

    - name: Print registry and namespace
      run: |
        echo "Registry: ${{ secrets.ALIYUN_REGISTRY }}"
        echo "Namespace: ${{ secrets.ALIYUN_NAME_SPACE }}"

    - name: Build and push image Aliyun
      run: |
        # 数据预处理,判断镜像是否重名
        declare -A duplicate_images
        declare -A temp_map
        while IFS= read -r line || [ -n "$line" ]; do
            # 忽略空行与注释
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                continue
            fi
            # 处理镜像名称和标签
            image_name=$(echo "$line" | awk '{print $1}')
            image_tag=$(echo "$line" | awk '{print $2}')
            # 构建Docker镜像
            docker build -t ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/$image_name:$image_tag .
            # 推送Docker镜像到阿里云
            docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/$image_name:$image_tag
        done < images.txt

    - name: Check for errors
      run: |
        if [ $? -ne 0 ]; then
          echo "Error occurred during build or push"
          exit 1
        fi
